source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

# App Dependencies

# Dependencies for all targets (including extensions)
def core_pods
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end

target 'PrumtMe' do
    core_pods
end
